name: ocupa2_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Red y estado
  http: ^1.6.0
  provider: ^6.1.2
  intl: ^0.19.0

  # Almacenamiento local
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^11.0.0

  # Multimedia
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
